### PR TITLE
Disable CORS

### PR DESCRIPTION
**Pull request by vigejolla**
This is a first step towards allowing hydrogen to run with ESR78

### CODE REVIEW

**Comment by vigejolla** [comment]
Next step would be disabling serviceWorkers. I don't have time to do that, at least right now. Hopefully someone else does.

**Comment by thigg** [comment]
I will, I am just waiting for the EA-release ;)

**Comment by vigejolla** [comment]
> Next step would be disabling serviceWorkers. I don't have time to do that, at least right now. Hopefully someone else does.

Looks like flypig already managed to do that: https://github.com/thigg/hydrogen-web/pull/1

**Comment by thigg** [comment]
@vigejolla 

Is this already mentioned in the documentation of WebView? I haven't seen it there anywhere.
```
WebEngineSettings.setPreference("security.disable_cors_checks", true, WebEngineSettings.BoolPref)
```

Also it would be interesting to know, if I could do it better and just allow file instead of disabling cors completly.

**Comment by b100dian** [comment]
Hi, is this still needed on https://sailfishos-chum.github.io/apps/harbour-hydrogen/ ?

**Comment by vigejolla** [comment]
> Hi, is this still needed on https://sailfishos-chum.github.io/apps/harbour-hydrogen/ ?

Most likely not needed anymore, i.e. after implementing the web server.

**Pull request closed without merging**
